stages:
  - deploy

before_script:
- whoami
- eval $(ssh-agent -s)
- ssh-add
- BASEPATH="/etc/puppetlabs/code/environments/"
- export PATH=/opt/puppetlabs/bin:$PATH

Sync changes to Puppet Master:
  stage: deploy
  script:
    - sudo git -C $BASEPATH fetch --all 
    - sudo git -C $BASEPATH reset --hard "origin/$CI_COMMIT_REF_NAME"
    - sudo librarian-puppet install --clean --verbose
