stages:
  - deploy

before_script:
- whoami
- eval $(ssh-agent -s)
- ssh-add
- BASEPATH="/etc/puppetlabs/code/environments/"

Sync changes to Puppet Master:
  stage: deploy
  script:
    - sudo git -C $BASEPATH fetch --all
    - cd $BASEPATH/$CI_COMMIT_REF_NAME/
    - pwd
    - sudo git reset --hard "origin/$CI_COMMIT_REF_NAME" .
    - sudo librarian-puppet install --clean --verbose --path=$BASEPATH/$CI_COMMIT_REF_NAME/modules/