stages:
  - deploy

before_script:
- whoami
- eval $(ssh-agent -s)
- ssh-add
- BASEPATH="/etc/puppetlabs/code/environments/"
- sudo puppet agent -t 

Sync changes to Puppet Master:
  stage: deploy
  script:
    - sudo git -C $BASEPATH fetch --all 
    - sudo git -C $BASEPATH/$CI_COMMIT_REF_NAME reset --hard "origin/$CI_COMMIT_REF_NAME"
    - sudo librarian-puppet install --clean --verbose