stages:
  - deploy

move to test:
  stage: deploy
  script:
    - whoami
    - sudo rsync -avz * /etc/puppetlabs/code/environments/$CI_COMMIT_REF_NAME/
    - sudo chown -R :root /etc/puppetlabs/code/environments/$CI_COMMIT_REF_NAME/