stages:
  - deploy

move to test:
  stage: deploy
  script:
    - whoami
    #- sudo rsync -avz * /etc/puppetlabs/code/environments/$CI_COMMIT_REF_NAME/
    #- sudo chown -R root:root /etc/puppetlabs/code/environments/$CI_COMMIT_REF_NAME/
    - BASEPATH = /etc/puppetlabs/code/environments/
    - git -C $BASEPATH fetch --all 
    - git -C $BASEPATH reset --hard "origin/$CI_COMMIT_REF_NAME"
